=== jorge-test/test-repo/src/main/api/api-create-user-out-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://jsonschema.net",
  "type": "object",
  "properties": {
    "user_email": {
      "id": "http://jsonschema.net/user_email",
      "type": "string"
    },
    "username": {
      "id": "http://jsonschema.net/username",
      "type": "string"
    },
    "user_information": {
      "id": "http://jsonschema.net/user_information",
      "type": "object",
      "properties": {}
    },
    "email_verified": {
      "id": "http://jsonschema.net/email_verified",
      "type": "boolean"
    },
    "user_id": {
      "id": "http://jsonschema.net/user_id",
      "type": "string"
    },
    "avatar": {
      "id": "http://jsonschema.net/avatar",
      "type": "string"
    },
    "nickname": {
      "id": "http://jsonschema.net/nickname",
      "type": "null"
    },
    "identities": {
      "id": "http://jsonschema.net/identities",
      "type": "array",
      "items": {
        "id": "http://jsonschema.net/identities/0",
        "type": "object",
        "properties": {
          "connection": {
            "id": "http://jsonschema.net/identities/0/connection",
            "type": "string"
          },
          "user_id": {
            "id": "http://jsonschema.net/identities/0/user_id",
            "type": "string"
          },
          "provider": {
            "id": "http://jsonschema.net/identities/0/provider",
            "type": "string"
          },
          "isSocial": {
            "id": "http://jsonschema.net/identities/0/isSocial",
            "type": "boolean"
          }
        }
      }
    },
    "updated_at": {
      "id": "http://jsonschema.net/updated_at",
      "type": "string"
    },
    "created_at": {
      "id": "http://jsonschema.net/created_at",
      "type": "string"
    },
    "application_information": {
      "id": "http://jsonschema.net/application_information",
      "type": "object",
      "properties": {}
    }
  },
  "required": [
    "user_email",
    "username",
    "user_information",
    "email_verified",
    "user_id",
    "avatar",
    "nickname",
    "identities",
    "updated_at",
    "created_at",
    "application_information"
  ]
}

=== jorge-test/test-repo/src/main/api/api-create-user-out-example.json
{
  "user_email": "john.doe4@gmail.com",
  "username": "johndoe5",
  "user_information": {
  },
  "email_verified": false,
  "user_id": "auth0|571e653acda2f77e02ef6b80",
  "avatar": "https://s.gravatar.com/avatar/cd541925222efc34dbc51a715013ed5e?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fjo.png",
  "nickname": null,
  "identities": [
    {
      "connection": "MotherShip",
      "user_id": "571e653acda2f77e02ef6b80",
      "provider": "auth0",
      "isSocial": false
    }
  ],
  "updated_at": "2016-04-25T18:43:06.448Z",
  "created_at": "2016-04-25T18:43:06.448Z",
  "application_information": {}
}
